rails g scaffold newsletter ` 
subject:string `
date:date `
utm_source:string `
utm_medium:string `
utm_campaign:string `
hero_utm_medium:string `
hero_title:string `
hero_url:string `
hero_description:string `
hero_image_url:string `
course_utm_medium:string `
course_one_title:string `
course_two_title:string `
course_three_title:string `
course_four_title:string `
course_five_title:string `
course_six_title:string `
course_one_description:string `
course_two_description:string `
course_three_description:string `
course_four_description:string `
course_five_description:string `
course_six_description:string `
course_one_url:string `
course_two_url:string `
course_three_url:string `
course_four_url:string `
course_five_url:string `
course_six_url:string `
course_one_author:string `
course_two_author:string `
course_three_author:string `
course_four_author:string `
course_five_author:string `
course_six_author:string `
course_one_image:string `
course_two_image:string `
course_three_image:string `
course_four_image:string `
course_five_image:string `
course_six_image:string `
upcoming_one:string `
upcoming_two:string `
upcoming_three:string `
upcoming_four:string `
popular_one:string `
popular_two:string `
popular_three:string `
popular_four:string `
popular_url_one:string `
popular_url_two:string `
popular_url_three:string `
popular_url_four:string